apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: quay.io/choudeshell/busybox:codemash
      name: busybox
      volumeMounts:
      - name: pvc
        mountPath: /data
      command: [ "sh", "-c"]
      args:
      - sleep 10000
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: local-path-pvc2