apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  annotations:
    deployment.kubernetes.io/revision: "2"
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: quay.io/choudeshell/whoami:codemash