apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whoami-sset
spec:
  serviceName: whoami-service
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: traefik/whoami:v1.10.1